---
- name: Service ready message template generator
  hosts: localhost
  vars_files:
    - vars.yml
  tasks:
    - name: Create output directory
      file:
        path: "{{ output_dir }}"
        recurse: yes
        state: directory

    - name: Create service ready message mjml
      template:
          src: template.mjml.j2
          dest: "{{ output_dir }}/service-ready-message-template.mjml"

    - name: reset as variables
      replace:
        path: "{{ output_dir }}/service-ready-message-template.mjml"
        regexp: '--curly'
        replace: "{{ '{{' |string }}"

    - name: reset as variables
      replace:
        path: "{{ output_dir }}/service-ready-message-template.mjml"
        regexp: 'curly--'
        replace: "{{ '}}' |string }}"

    - name: Install npm on MacOSX
      package:
        name: npm 
        state: latest
      when: ansible_distribution == "MacOSX"

    - name: Install npm RHEL
      become: true
      package:
        name: npm 
        state: latest
      when: ansible_distribution != "MacOSX"

    - name: Install mjml node.js package
      npm:
        name: mjml
        path: "{{ output_dir }}"
        version: '4.13.0'

    - name: Convert mjml to html
      shell: >-
        {{ output_dir }}/node_modules/.bin/mjml
        {{ output_dir }}/service-ready-message-template.mjml
        > {{ output_dir }}/index.html

    - name: Open html in browser
      ignore_errors: true
      shell: >-
        open {{ output_dir }}/index.html