---
- name: Service ready message template generator
  hosts: localhost
  vars_files:
    - vars.yml
  vars:
    curlytag: "{{ '{{' |string }}"
  tasks:
    - name: Create service ready message mjml
      template:
          src: template.mjml.j2
          dest: service-ready-message-template.mjml

    - name: reset as variables
      replace:
        path: service-ready-message-template.mjml
        regexp: '--curly'
        replace: "{{ '{{' |string }}"

    - name: reset as variables
      replace:
        path: service-ready-message-template.mjml
        regexp: 'curly--'
        replace: "{{ '}}' |string }}"

    - name: Install npm
      become: true
      package:
        name: npm 
        state: latest

    - name: Install mjml node.js package.
      npm:
        name: mjml
        path: /tmp/mjml/
        version: '4.13.0'

    - name: Convert mjml to html
      shell: >-
        /tmp/mjml/node_modules/.bin/mjml
        service-ready-message-template.mjml
        > index.html