---
- name: Service ready message template generator
  hosts: localhost
  tasks:
    - name: Set variables file path
      set_fact:
        template_vars_file: ./vars.yml
      when: template_vars_file is not defined

    - name: Include variables file
      include_vars: "{{ template_vars_file }}"

    - name: Create output directory
      file:
        path: "{{ output_dir }}/data"
        recurse: yes
        state: directory

    - name: Create service ready message mjml
      template:
          src: template.mjml.j2
          dest: "{{ output_dir }}/data/service-ready-message-template.mjml"

    - name: reset variables
      replace:
        path: "{{ output_dir }}/data/service-ready-message-template.mjml"
        regexp: '--curly'
        replace: "{{ '{{' |string }}"

    - name: reset variables
      replace:
        path: "{{ output_dir }}/data/service-ready-message-template.mjml"
        regexp: 'curly--'
        replace: "{{ '}}' |string }}"

    - name: Install npm
      when: install_npm | default(false)
      block:
        - name: Install npm on MacOSX
          package:
            name: npm 
            state: latest
          when: ansible_distribution == "MacOSX"

        - name: Install npm RHEL
          become: true
          package:
            name: npm 
            state: latest
          when: ansible_distribution != "MacOSX"

    - name: Install mjml node.js package
      npm:
        name: mjml
        path: "{{ output_dir }}"
        version: '4.13.0'
      when: install_mjml | default(true)
    
    - name: Convert mjml to html
      shell: >-
        {{ output_dir }}/node_modules/.bin/mjml
        {{ output_dir }}/data/service-ready-message-template.mjml
        > {{ output_dir }}/data/index.html

    - name: copy index file as jinja template
      copy:
        src: "{{ output_dir }}/data/index.html"
        dest: "{{ output_dir }}/data/service-ready-message-template.html.j2"
        remote_src: yes

    - name: Open html in browser
      ignore_errors: true
      shell: >-
        open {{ output_dir }}/data/index.html